[package]
name = "visual-hash"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.9.0"
image = "0.23.14"
imageproc = "0.23.0"
clap = "4.5.1"
sha2 = "0.10.8"


[dev-dependencies]
assert-panic = "1.0.1"
