[package]
name = "visual-hash"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
image = "0.23.14"
imageproc = "0.24.0"

[dev-dependencies]
assert-panic = "0.4.0"
