name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build the Docker image from the Dockerfile in .devcontainer
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ./.devcontainer
        file: ./.devcontainer/Dockerfile
        load: true
        tags: rust_project:latest

    # Run cargo build inside the Docker container
    - name: Cargo Build
      run: docker run --rm -v ${{ github.workspace }}:/usr/src/vh rust_project:latest cargo build --verbose

    # Run cargo test inside the Docker container
    - name: Cargo Test
      run: docker run --rm -v ${{ github.workspace }}:/usr/src/vh rust_project:latest cargo test --verbose
